### ISSUE TITLE
Не запускается ios приложение на m1 

### ISSUE THREAD

**Issue by Melber17** [volga-volga/react-native-yamap#139]
При установке **react-native-yamap** и **cocoapods** падает такая ошибка:

```
`ld: in ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file 'os/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


2022-07-04 09:21:05.475 xcodebuild[42405:123888] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-04 09:21:05.476 xcodebuild[42405:123888] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **
`
```

Пробовал использовать как новую **^4.0.17**, так и старую **^4.0.3** версию библиотеки.
Использую Xcode `13.4.1 ` версии, мак на m1.

**Comment by tegozen** [comment]
есть вероятность, что если исправить версию основной либы то проблема уйдет, но там не обратно совместимые изменения видимо. методов не хватает. Сейчас пытаюсь разобраться проблема в коде или что-то не установилось.
```
require "json"

Pod::Spec.new do |s|
    package = JSON.parse(File.read(File.join(File.dirname(__FILE__), "package.json")))
    s.name         = "RNYamap"
    s.version      = package["version"]
    s.summary      = package["description"]
    s.homepage     = "vvdev.ru"
    s.license      = "MIT"
    s.author       = { package["author"]["name"] => package["author"]["email"] }
    s.platform     = :ios, "9.0"
    s.source       = { :git => "https://github.com/author/RNYamap.git", :tag => "master" }
    s.source_files = "ios/**/*.{h,m}"
    # s.requires_arc = true

    s.dependency "React"
    s.dependency "YandexMapsMobile", "4.1.0-full"
end
```

**Comment by tegozen** [comment]
Приложение собралось видимо ошибку сборки arm в этой версии YandexMapsMobile все же починили, но так как я не знаю obj-c все ошибки отсутствия методов я решил комментированием и приложение не стартует уже по фаталам кода.
Ну хотя бы собирается. В общем нужно либо самим разбираться в совестимости этого порта к основной либе последней версии или ждать пока текущий разработчик апнет свою версию до последней версии YandexMapsMobile

**Comment by tegozen** [comment]
MapKit SDK 4.1.0 (May 18, 2022)
List of changes
Changes to the map

A new schema layer VMAP3 which supports several modes of displaying map. The following modes are currently available: Default, Transport and Navigation.
Added correction of object size on the map based on latitude to compensate for the distortion created by the Mercator projection.
You can now add text to point map objects.
Of the two classes PolylineMapObject and ColoredPolylineMapObject, only PolylineMapObject is now used because it covers the functions of both classes.
MapObject.getParent [now returns](https://github.com/yandex/mapkit-android-demo/issues/258) BaseMapObjectCollection, which is a common parent for MapObjectCollection and ClusterizedPlacemarkCollection.
Renamed ZoomFocusPointMode to GestureFocusPointMode. GestureFocusPoint now also affects rotation in AffectsAllGestures mode.
Fixed jerks when scrolling the map.
Optimized memory consumption.
Added the map inspector API for writing UI tests: Map.visibleObjects.
A new style format for GeoJSON layers.
Made the map more customizable: you can now change icon color.
Added the ability to set the 3D model dimensions in pixels.
Other changes

Added the ability to build routes for cargo transport taking into account its parameters, including dimensions (length, width, and height), weight, maximum weight allowed, axle load, and load. If a route cannot be built without violating the vehicle parameter restrictions, a route with violations is built, and you can see where the violations occur.
For Android only

The minimum supported version is now 5.0.
For iOS only

Work in emulators with an M1 processor is [supported](https://github.com/yandex/mapkit-ios-demo/issues/106).
Build with Xcode 13.3 is [supported](https://github.com/yandex/mapkit-ios-demo/issues/141).
The SDK is now delivered as an xcframework.
The minimum supported iOS version is now 12 (13 for an emulator with an M1 processor).

**Comment by tegozen** [comment]
После миллиарда пересборок и обновлений всего чего можно запустилось на эмуляторе
https://prnt.sc/wlBElXF57MoW - все изменения.
на девайс по прежнему не собирается

**Comment by GilTRipper** [comment]
+1 cобирается на симуляторе, но бьет ошибку при сборке на реально устройстве

**Comment by tegozen** [comment]
В общем. xcode 13.2.1 позволяет собрать приложение на устройство.
https://developer.apple.com/download/all/?q=xcode%2013.2.1
Можно поставить его рядом с последним xcode - они работают отдельно. Единственное что нужно - переключить консольную версию xcode
xcode-preferences-locations-command line tools (выбираете нужную вам)

**Comment by tegozen** [comment]
Однако все же я считаю это костылем(
Но пока что думаю обновление этой библиотеки невозможно в связи с тем, что основная библиотека яндекс карт поменяла свое апи в новой версии

**Comment by GilTRipper** [comment]
@ownikss планируется на ближайшее будущее обновление до 4.1.0-full?

**Comment by SokolovRU** [comment]
Эмулятор вроде открывается.


![Simulator Screen Shot - iPhone 13 - 2022-07-10 at 17 51 31](https://user-images.githubusercontent.com/105442172/178149988-4dcadb89-bc1c-486b-bd5a-d25540423d4c.png)

**Comment by Melber17** [comment]
@SokolovRU не думаете ли вы что запуск с rosseta является костылем? По хорошему бы подождать тогда поддержку на m1 архитектуру

**Comment by Melber17** [comment]
На эмуляторе запустилась карта с rosseta 🚀
@SokolovRU если же есть только сетка, а самой карты нету, то это дело в токене?
<img width="420" alt="image" src="https://user-images.githubusercontent.com/63192915/178421297-da68be2a-d22d-43c9-b67e-155406613e5a.png">

**Comment by Melber17** [comment]
На реальном девайсе история такая же, выдает ошибку даже при помощи rosseta.
А новый проект создать нету смысла. Потому что делаю не все с нуля 😥 
```
Mobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file /ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64
```

**Comment by SokolovRU** [comment]
@Melber17 - я не знаю почему у тебя голая сетка. может быть ошибка в ref или приложение просто не отрисовывает ( возможно плохой интернет ) 
свяжись со мной в тг - давай решать проблему вместе! @thebestpl 

мне Яндекс карты тоже нужны, и если реальное устройство не работает, то это проблема общая

**Comment by GilTRipper** [comment]
@Melber17 голая карта появляется при не валидном API-Key. 
Нужен апи ключ именно для MapKit.

**Comment by Melber17** [comment]
@GilTRipper да даже с тестовым валидным нету карты
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/63192915/178477585-64c7a264-1d05-4d72-8d9c-d5435656afb4.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/63192915/178477495-d483dea3-cf9c-44a0-b1c6-9d5a0af58b88.png">

**Comment by tegozen** [comment]
> @GilTRipper да даже с тестовым валидным нету карты. Через раз еще отображается розовый фон <img alt="image" width="1165" src="https://user-images.githubusercontent.com/63192915/178477585-64c7a264-1d05-4d72-8d9c-d5435656afb4.png">
> 
> <img alt="image" width="370" src="https://user-images.githubusercontent.com/63192915/178477495-d483dea3-cf9c-44a0-b1c6-9d5a0af58b88.png">

скажи мне на**? - зачем писать в тикет о том что не собирается приложение с этим пакетом - вообще не связанную с этим информацию? ты умеешь пользоваться issue? или ты думаешь тут сидит круглосуточная поддержка которая решит проблемы твоего кода?

**Comment by KamilSadekov** [comment]
работает штатно помимо жесткой сенсы при малейшем скролле на эмуляторе (но как понял подобная штука фиксится на реальных устройствах), проблемы начинаются при архивации в xcode 13+ ошибка:(YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64), но всё четко с xcode 12 
Но из-за политики Apple не могу задистрибьютить приложуху на версии xcode < 13 , есть ли решения на этот счет ? )
m1
"react-native-yamap": "^4.0.19",
"react-native": "0.67.4",
xcode: 13.4.1

**Comment by Djhitman** [comment]
все еще крашится

**Comment by ksielyov** [comment]
+
