### ISSUE TITLE
Adding theme for maps

### ISSUE THREAD

**Issue by Metallistener** [volga-volga/react-native-yamap#27]
Hi! I would like to know about adding theme for maps. Do you plan to add **prop** for this feature?

**Comment by ownikss** [comment]
Hi! Do you mean [this styling](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/style-docpage/#style__format) or just night mode for mapkit?

MapStyle does not work for android because I use old version of mapkit. See [issue](https://github.com/yandex/mapkit-android-demo/issues/116)

I can add new props in next release.

**Comment by ownikss** [comment]
NightMode and styling implemented in version 1.0.18. Documentation updated
